
- include_vars:
    file: users.yml

- name: Add new userers or remove users
  user:
    name: "{{item.username}}"
    shell: /bin/bash
    password: "{{ item.password}}"
    state: "{{ item.state}}"
    remove: "{{ item.remove}}"
  with_items: '{{users}}'

- name: Add users to the Sudoers
  copy:
    dest: "/etc/sudoers.d/{{ item.username}}"
    content: "{{ item.username}}  ALL=(ALL) ALL"
  when: item.state == "present"
  with_items: '{{users}}'

- name: Deploy SSH Key for new users or remove them
  authorized_key:
    user: "{{ item.username}}"
    key: "{{ lookup('file', 'public-keys/{{item.username}}') }}"
  notify: restart ssh
  when: item.state == "present"
  with_items: '{{users}}'

- name: Remove User from Sudoers
  file:
    path: "/etc/sudoers.d/{{ item.username}}"
    state: absent
  when: item.state == "absent"
  with_items: '{{users}}'
